openapi: 3.1.0
info:
  title: API сервер для демо-проекта «6 городов».
  description: |-
    * Список объявлений в сервисе «6 городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: authors
    description: Действия с авторами объявлений.
